services:
  filmapi.repository.film:
    class: FilmApiBundle\Repository\MySQLFilmRepository
    public: false
    arguments:
      - "@doctrine.orm.default_entity_manager"

  filmapi.decorator.film:
    class: FilmApiBundle\Decorators\FilmDecorator
    decorates: filmapi.repository.film
    public: false
    arguments: ['@filmapi.decorator.film.inner','@debug.event_dispatcher']

  filmapi.command_handler.createFilm:
    class     : FilmApi\Application\CommandHandler\Film\CreateFilmHandler
    public    : true
    arguments :
      - "@filmapi.decorator.film"

  filmapi.command_handler.deleteFilm:
    class     : FilmApi\Application\CommandHandler\Film\DeleteFilmHandler
    public    : true
    arguments :
      - "@filmapi.decorator.film"

  filmapi.command_handler.updateFilm:
    class     : FilmApi\Application\CommandHandler\Film\UpdateFilmHandler
    public    : true
    arguments :
      - "@filmapi.decorator.film"

  filmapi.command_handler.findFilmByTitle:
      class     : FilmApi\Application\CommandHandler\Film\FindByTitleHandler
      public    : true
      arguments :
        - "@filmapi.decorator.film"

  filmapi.command_handler.findFilmById:
      class     : FilmApi\Application\CommandHandler\Film\FindFilmByIdHandler
      public    : true
      arguments :
        - "@filmapi.decorator.film"        

  filmapi.command_handler.findAllFilms:
      class     : FilmApi\Application\CommandHandler\Film\FindAllFilmsHandler
      public    : true
      arguments :
        - "@filmapi.decorator.film"        

  filmapi.listener.film_created:
    class     : FilmApiBundle\EventListener\FilmListener
    arguments : ['@cache.app']
    tags      : 
        - {name : kernel.event_listener, event: film.created}               

  filmapi.listener.film_deleted:
    class     : FilmApiBundle\EventListener\FilmListener
    arguments : ['@cache.app']
    tags      : 
        - {name : kernel.event_listener, event: film.deleted}               

  filmapi.listener.find_film_by_title:
    class     : FilmApiBundle\EventListener\FilmListener
    arguments : ['@cache.app']
    tags      : 
        - {name : kernel.event_listener, event: film.find_by_title}               

  filmapi.listener.find_film_by_id:
    class     : FilmApiBundle\EventListener\FilmListener
    arguments : ['@cache.app']
    tags      : 
        - {name : kernel.event_listener, event: film.find_by_id}                       