create_film:
  path: /film
  defaults: { _controller: FilmApiBundle:Film:createFilm}
  methods: [POST]

delete_film:
  path: /film
  defaults: { _controller: FilmApiBundle:Film:deleteFilm}
  methods: [DELETE]

update_film:
  path: /film
  defaults: { _controller: FilmApiBundle:Film:updateFilm}
  methods: [PUT]

find_by_title:
  path: /film
  defaults: { _controller: FilmApiBundle:Film:findFilmByTitle}
  methods: [GET]
  requirements:
    name: \w+


create_actor:
  path: /actor
  defaults: { _controller: FilmApiBundle:Actor:createActor }
  methods: [POST]

delete_actor:
  path: /actor
  defaults: { _controller: FilmApiBundle:Actor:deleteActor }
  methods: [DELETE]

find_all_actors:
  path: /actors
  defaults: { _controller: FilmApiBundle:Actor:findAllActors }
  methods: [GET]

find_actor_by_id:
  path: /actor_id
  defaults: { _controller: FilmApiBundle:Actor:findActorById }
  methods: [GET]  
  requirements:
    name: \d+

find_actor_by_name:
  path: /actor
  defaults: { _controller: FilmApiBundle:Actor:findActorByName }
  methods: [GET]  
  requirements:
    name: \w+

list_actor_by_id_web:
  path    : /web/{_locale}/actor
  defaults: {_controller: FilmApiBundle:Actor:findActorByIdWeb}
