parameters:

services:
  filmapi.repository.actor:
    class: FilmApiBundle\Repository\MySQLActorRepository
    public: false
    arguments:
      - "@doctrine.orm.default_entity_manager"
      - "@cache.app"

  filmapi.decorator.actor:
    class: FilmApiBundle\Decorators\ActorDecorator
    decorates: filmapi.repository.actor
    public: false
    arguments: ['@filmapi.decorator.actor.inner','@cache.app']

  filmapi.command_handler.createActor:
    class     : FilmApi\Application\CommandHandler\Actor\CreateActorHandler
    public    : true
    arguments :
      - "@filmapi.decorator.actor"


  
