parameters:

services:
  filmapi.repository.actor:
    class: FilmApiBundle\Repository\MySQLActorRepository
    public: false
    arguments:
      - "@doctrine.orm.default_entity_manager"
      - "@cache.app"

  filmapi.decorator.actor:
    class: FilmApiBundle\Decorators\ActorDecorator
    decorates: filmapi.repository.actor
    public: false
    arguments: ['@filmapi.decorator.actor.inner','@cache.app']

  filmapi.command_handler.createActor:
    class     : FilmApi\Application\CommandHandler\Actor\CreateActorHandler
    public    : true
    arguments :
      - "@filmapi.decorator.actor"

  filmapi.command_handler.findAllActors:
    class     : FilmApi\Application\CommandHandler\Actor\FindAllActorsHandler
    public    : true
    arguments :
      - "@filmapi.decorator.actor"

  filmapi.command_handler.findActorByName:
      class     : FilmApi\Application\CommandHandler\Actor\FindActorByNameHandler
      public    : true
      arguments :
        - "@filmapi.decorator.actor"

  filmapi.command_handler.findActorById:
      class     : FilmApi\Application\CommandHandler\Actor\FindActorByIdHandler
      public    : true
      arguments :
        - "@filmapi.decorator.actor"        

  filmapi.command_handler.updateActor:
      class     : FilmApi\Application\CommandHandler\Actor\UpdateActorHandler
      public    : true
      arguments :
        - "@filmapi.decorator.actor"        

  filmapi.command_handler.deleteActor:
      class     : FilmApi\Application\CommandHandler\Actor\DeleteActorHandler
      public    : true
      arguments :
        - "@filmapi.decorator.actor"        


  
